### ISSUE TITLE
Support multiple language string files in pod spec

### ISSUE THREAD

**Issue by soffes** [soffes/SAMCategories#1]
I noticed there was an issue for new copy resources in the CocoaPods repo. Guessing this is addressed in that. Until then, a workaround, would be awesome.

I tired:

``` ruby
spec.resources = 'SAMCategories/Strings/*.lproj/*.strings'
```

But that just copied one of them from a random language. Makes sense since it's not copying the folders. Not sure how to solve this or if it's supported at all.

Would love some help, @alloy.

**Comment by alloy** [comment]
You must make one resource bundle dir, either by just creating that layout in the repo or by creating a resource bundle target in your xcodeproj and build that from a `pre_install` hook, and then reference _just_ that resource bundle dir so that the complete bundle dir is copied into the app bundle.

You cannot just copy language files into the app bundle, because that would collide with other language files.

HTH.

**Comment by soffes** [comment]
Makes sense. Thanks!

**Comment by alloy** [comment]
PS: You’ll have to use something like `NSLocalizedStringFromTableInBundle` to reference the localized strings.

**Comment by soffes** [comment]
Ya, that's how I was doing it in SSToolkit. It will be a lot easier to just copy the `.bundle` instead of the `pre_install` silliness. :)

**Comment by soffes** [comment]
Fixed in cb81a9e859bc0cb726e0feb63e7d786e218b1e3d
